In [1]:
import pandas as pd

In [2]:
demographics_pd = pd.read_csv("DEMOGRAPHICS.csv")
demographics_pd

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,Strata_Determining_Factors,Number_Counties,Population_Size,Min_Population_Size,...,Max_Black,Native_American,Min_Native_American,Max_Native_American,Asian,Min_Asian,Max_Asian,Hispanic,Min_Hispanic,Max_Hispanic
0,1,1,Autauga,Alabama,AL,29,"frontier status, population size, poverty, age",37,48612,28447,...,17.3,0.5,0.1,1.1,0.6,0.2,2.2,1.7,0.8,19.2
1,1,3,Baldwin,Alabama,AL,16,"frontier status, population size, poverty, age",27,162586,118395,...,14.1,0.5,0.1,1.1,0.4,0.4,3.3,2.3,0.8,13.7
2,1,5,Barbour,Alabama,AL,51,"frontier status, population size, poverty, age...",33,28414,27269,...,50.7,0.4,0.2,7.1,0.3,0.2,2.3,3.1,1.0,67.7
3,1,7,Bibb,Alabama,AL,42,"frontier status, population size, poverty, age",53,21516,8134,...,35.4,0.3,0.1,2.6,0.1,0.1,1.5,1.4,1.2,46.9
4,1,9,Blount,Alabama,AL,28,"frontier status, population size, poverty, age",39,55725,29009,...,20.5,0.5,0.1,0.9,0.2,0.3,2.2,6.3,0.8,6.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,56,37,Sweetwater,Wyoming,WY,77,"frontier status, population size",15,37975,26995,...,1.6,1.1,1.0,41.5,1.0,0.3,1.5,10.3,2.8,71.5
3137,56,39,Teton,Wyoming,WY,78,"frontier status, population size, poverty, age",43,19032,765,...,1.6,0.4,0.4,16.2,0.8,0.0,3.2,10.2,1.1,22.6
3138,56,41,Uinta,Wyoming,WY,38,"frontier status, population size, poverty, age",35,19939,7467,...,6.3,1.1,0.2,1.9,0.3,0.2,1.3,5.9,0.6,13.8
3139,56,43,Washakie,Wyoming,WY,82,"frontier status, population size, poverty, age",37,7933,1573,...,0.9,0.8,0.1,2.8,0.7,0.1,0.5,12.1,0.6,15.9
3140,56,45,Weston,Wyoming,WY,78,"frontier status, population size, poverty, age",43,6671,765,...,1.6,1.4,0.4,16.2,0.2,0.0,3.2,2.3,1.1,22.6

In [3]:
risk_factors_pd = pd.read_csv("RISKFACTORSANDACCESSTOCARE.csv")
risk_factors_pd

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,No_Exercise,CI_Min_No_Exercise,CI_Max_No_Exercise,Few_Fruit_Veg,...,Diabetes,CI_Min_Diabetes,CI_Max_Diabetes,Uninsured,Elderly_Medicare,Disabled_Medicare,Prim_Care_Phys_Rate,Dentist_Rate,Community_Health_Center_Ind,HPSA_Ind
0,1,1,Autauga,Alabama,AL,29,27.8,20.7,34.9,78.6,...,14.2,9.1,19.3,5690,4762,1209,45.3,22.6,1,2
1,1,3,Baldwin,Alabama,AL,16,27.2,23.2,31.2,76.2,...,7.2,5.2,9.3,19798,22635,3839,67.0,30.8,1,2
2,1,5,Barbour,Alabama,AL,51,-1111.1,-1111.1,-1111.1,-1111.1,...,6.6,2.0,11.3,5126,3288,1092,45.8,24.6,1,2
3,1,7,Bibb,Alabama,AL,42,-1111.1,-1111.1,-1111.1,86.6,...,13.1,4.7,21.5,3315,2390,974,41.8,18.6,1,1
4,1,9,Blount,Alabama,AL,28,33.5,26.3,40.6,74.6,...,8.4,4.4,12.4,8131,5019,1300,16.2,10.8,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,56,37,Sweetwater,Wyoming,WY,77,21.9,19.8,24.1,80.7,...,5.3,4.2,6.4,5477,3260,572,50.0,52.7,2,1
3137,56,39,Teton,Wyoming,WY,78,9.6,7.3,11.9,68.8,...,2.4,1.4,3.4,1846,1393,82,147.1,57.8,2,2
3138,56,41,Uinta,Wyoming,WY,38,23.4,20.5,26.3,83.1,...,4.8,3.4,6.2,3007,1431,357,65.2,40.1,2,1
3139,56,43,Washakie,Wyoming,WY,82,23.2,18.8,27.6,78.1,...,9.4,6.6,12.1,1178,1338,136,50.4,50.4,1,1
3140,56,45,Weston,Wyoming,WY,78,31.3,26.1,36.6,75.4,...,5.7,3.4,8.0,867,1072,143,45.0,30.0,2,1

In [4]:
vulnerable_pd = pd.read_csv("VUNERABLEPOPSANDENVHEALTH.csv")
vulnerable_pd

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,No_HS_Diploma,Unemployed,Sev_Work_Disabled,Major_Depression,...,Shig_Rpt_Ind,Shig_Exp,Toxic_Chem,Carbon_Monoxide_Ind,Nitrogen_Dioxide_Ind,Sulfur_Dioxide_Ind,Ozone_Ind,Particulate_Matter_Ind,Lead_Ind,EH_Time_Span
0,1,1,Autauga,Alabama,AL,29,6690,774,1727,2680,...,3,11,2883197,1,1,1,1,1,1,1999-2003
1,1,3,Baldwin,Alabama,AL,16,20254,2533,4933,9354,...,4,13,35664,1,1,1,2,1,1,2001-2003
2,1,5,Barbour,Alabama,AL,51,6729,569,1302,1618,...,3,16,49874,1,1,1,1,1,1,1999-2003
3,1,7,Bibb,Alabama,AL,42,5355,358,900,1218,...,3,16,7302,1,1,1,1,1,1,1994-2003
4,1,9,Blount,Alabama,AL,28,11181,819,2217,3164,...,4,5,889020,1,1,1,1,1,1,1999-2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,56,37,Sweetwater,Wyoming,WY,77,3081,688,817,2649,...,3,15,2781816,1,1,1,1,1,1,1999-2003
3137,56,39,Teton,Wyoming,WY,78,762,437,264,1455,...,4,7,364,1,1,1,1,1,1,1994-2003
3138,56,41,Uinta,Wyoming,WY,38,1842,389,408,1347,...,3,18,5664,1,1,1,1,1,1,1994-2003
3139,56,43,Washakie,Wyoming,WY,82,780,182,168,576,...,4,2,221000,1,1,1,1,1,1,1994-2003
3140,56,45,Weston,Wyoming,WY,78,700,128,245,504,...,4,3,91674,1,1,1,1,1,1,1994-2003

In [5]:
merged_pd = demographics_pd.merge(vulnerable_pd).merge(risk_factors_pd)

In [ ]:
merged_pd

In [6]:
merged_pd = merged_pd[merged_pd['Obesity'] > 0]
merged_pd = merged_pd[merged_pd['No_Exercise'] > 0]
merged_pd = merged_pd[merged_pd['Few_Fruit_Veg'] > 0]

In [7]:
for i in range(3141):
    if i in merged_pd.index:
        merged_pd["No_HS_Diploma"][i] = "{:.1f}".format(
            (float(merged_pd["No_HS_Diploma"][i]/merged_pd["Population_Size"][i]) * 1000)/10)
    else:
        pass

C:\Users\Valen\anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
<ipython-input-7-3a7a531a61f9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_pd["No_HS_Diploma"][i] = "{:.1f}".format(

In [8]:
for i in range(3141):
    if i in merged_pd.index:
        merged_pd["Major_Depression"][i] = "{:.1f}".format(
            (float(merged_pd["Major_Depression"][i]/merged_pd["Population_Size"][i]) * 1000)/10)
    else:
        pass

<ipython-input-8-2efb4b6e4f57>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_pd["Major_Depression"][i] = "{:.1f}".format(

In [15]:
for i in range(3141):
    if i in merged_pd.index:
        merged_pd["Non-White"][i] = 100 - merged_pd["White"][i]
    else:
        pass

<ipython-input-15-d1b1fd2266a3>:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [10]:
for i in range(3141):
    if i in merged_pd.index:
        if float(merged_pd["Uninsured"][i]/merged_pd["Population_Size"][i]) * 100 > 0:
            merged_pd["Uninsured"][i] = "{:.1f}".format(
                (float(merged_pd["Uninsured"][i]/merged_pd["Population_Size"][i]) * 1000)/10)
        else:
            merged_pd["Uninsured"][i] = 0.0
    else:
        pass

<ipython-input-10-442d3ccbf52d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_pd["Uninsured"][i] = "{:.1f}".format(
<ipython-input-10-442d3ccbf52d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_pd["Uninsured"][i] = 0.0

merged_pd["obesity"]

In [21]:
kept_cat = ["CHSI_County_Name", "CHSI_State_Name",
                        "Population_Size","Obesity","No_Exercise",
                        "Few_Fruit_Veg","Poverty","No_HS_Diploma","Major_Depression","Diabetes",
           "Non-White","Uninsured","High_Blood_Pres"]

cleaned_pd = merged_pd[kept_cat]

cleaned_pd = cleaned_pd[cleaned_pd['Obesity'] > 0]
cleaned_pd = cleaned_pd[cleaned_pd['No_Exercise'] > 0]
cleaned_pd = cleaned_pd[cleaned_pd['Few_Fruit_Veg'] > 0]
cleaned_pd = cleaned_pd[cleaned_pd['High_Blood_Pres'] > 0]
#cleaned_pd = cleaned_pd[cleaned_pd['Major_Depression'] > 0]
#cleaned_pd = cleaned_pd[cleaned_pd['No_HS_Diploma'] > 0]

cleaned_pd
cleaned_pd["Non-White"]df

,CHSI_County_Name,CHSI_State_Name,Population_Size,Obesity,No_Exercise,Few_Fruit_Veg,Poverty,No_HS_Diploma,Major_Depression,Diabetes,Non-White,Uninsured,High_Blood_Pres
0,Autauga,Alabama,48612,24.5,27.8,78.6,10.4,13.8,5.5,14.2,19.3,11.7,29.1
1,Baldwin,Alabama,162586,23.6,27.2,76.2,10.2,12.5,5.8,7.2,11.6,12.2,30.5
7,Calhoun,Alabama,112141,27.0,29.2,81.9,16.4,17.4,5.7,11.2,21.7,14.7,33.2
10,Chilton,Alabama,41744,31.2,30.3,82.8,14.9,22.7,5.6,6.0,11.7,14.7,26.5
21,Cullman,Alabama,79886,22.2,29.4,76.2,13.3,20.4,5.7,10.0,2.7,14.9,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,Sweetwater,Wyoming,37975,23.6,21.9,80.7,8.6,8.1,7.0,5.3,4.5,14.4,22.7
3137,Teton,Wyoming,19032,9.0,9.6,68.8,5.6,4.0,7.6,2.4,2.1,9.7,18.9
3138,Uinta,Wyoming,19939,22.7,23.4,83.1,10.6,9.2,6.8,4.8,2.5,15.1,22.5
3139,Washakie,Wyoming,7933,21.1,23.2,78.1,11.1,9.8,7.3,9.4,2.8,14.8,27.8
3140,Weston,Wyoming,6671,24.2,31.3,75.4,9.9,10.5,7.6,5.7,2.4,13.0,26.7

In [12]:
import plotly.express as px

In [1]:
px.scatter_matrix(cleaned_pd, dimensions = ["High_Blood_Pres","Poverty","No_Exercise","Non-White"], color = "Obesity")

NameError: name 'px' is not defined

In [14]:
cleaned_pd.to_csv("CleanedData.csv")